name: Python CI/CD Demo

# Trigger the workflow on push or PR
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repo
    - uses: actions/checkout@v3

    # 2️⃣ Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.3'

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # 4️⃣ Run tests
    - name: Run tests
      run: |
        pytest

    # 5️⃣ Deploy step (optional demo)
    - name: Deployment Step
      if: success()  # Only run if tests passed
      run: echo "Tests passed! Ready to deploy..."
